### ISSUE TITLE
Please offer an offline version of the wiki

### ISSUE THREAD

**Issue by JadianRadiator** [CraftTweaker/CraftTweaker-Documentation#114]
Please offer an offline version of the wiki.
The change to the wiki's current form broke it for my site ripper.
I need an offline version of the wiki for when I'm stuck offline but want to work on my modpack anyway.
I have to have the wiki as a manual or I can't do anything more than basic recipe addition/removal.
I have to be able to refer to the wiki as a manual for all of the mod support stuff.
I need an official offline version, as the change to the wiki's current form broke the copy that the site ripper I use makes.

**Comment by jaredlll08** [comment]
Download this repo as a zip file or clone it and use a markdown viewer?

**Comment by JadianRadiator** [comment]
That did it, thanks :)
I am using [this](https://typora.io/) to view/read the clones documentation.

**Comment by kindlich** [comment]
If you want to have the same experience as you would get from the online wiki follow these steps:

1. Use git to clone this repository to your computer
2. Install mkdocs (you will need python and pip installed on your computer as well)
3. Open the folder in which your mkdocs.yml file is located in your command prompt.
4. Run `mkdocs serve`
5. Then you can open your browser on `localhost:8000` and use your browser as if you were online.

That's how you install mkdocs locally for developing the wiki.
It also allows you to change stuff and view the effects directly in the browser, so you can fix typos and later file a PR, for example

**Comment by JadianRadiator** [comment]
This happens when I try the command.
https://hastebin.com/raw/imodesifad
