### ISSUE TITLE
Question about mob drops

### ISSUE THREAD

**Issue by TheFirstMinecrafter** [CraftTweaker/CraftTweaker-Documentation#121]
Hello, CraftTweaker devs. I was wondering if it was possible to target every single mob in the game (or just a mod at a time), and add all the items of a certain mod as drops to them? I know how to apply all items of a mod to a mob, but targeting every single mob doesn't seem to be possible. Is it?

**Comment by kindlich** [comment]
`game.entities` returns a list of IEntityDefinition, see [here](https://docs.blamejared.com/en/#Vanilla/Game/IGame)
