### ISSUE TITLE
Outdated Pictures in Contribution section

### ISSUE THREAD

**Issue by masterbobli** [CraftTweaker/CraftTweaker-Documentation#128]
When I was translating the wiki, I had to translate some text on the picture. The original picture looks like this.
![771548235375_ pic](https://user-images.githubusercontent.com/37212918/51596391-d347c500-1f33-11e9-98f8-849a81e35a4b.jpg)
But when I replicate it myself, I took a screenshot and found that the title of the commit box is different.
![781548235379_ pic](https://user-images.githubusercontent.com/37212918/51596432-e9ee1c00-1f33-11e9-8420-f852e918d8fc.jpg)
Clearly, the commit box's title "Commit changes" is replaced by "propose file change".
So I think it could be necessary to replace these pictures with the updated ones and change the wording in relevant sections of the wiki.

**Comment by kindlich** [comment]
The screenshot is from a branch on which you have push access.
The examples on how to contribute start with forking the wiki and then assume you work on your branch.

`Propose file change` means as much as `Fork, create a new branch with the commit and open a PR`
