### ISSUE TITLE
Can you add a way to remove a specific Tooltips

### ISSUE THREAD

**Issue by Fireztonez** [CraftTweaker/CraftTweaker-Documentation#146]
Hello,
I want to remove somes tooltips added directly by the mod author, because it doesn't work like it the tooltips said, but, the only function I can see on the CraftTweaker Wiki remove ALL tooltips, incliding the Item Name, the IItemStack ID, the mod name and everithing... A function like that, look to me completly useless...

So, only 2 thing I can do, for what I see, adding back manually ALL tootlips or, adding a tootips which contradicts the first one...

Minecraft: 1.12.2
Crafttweaker: 4.1.14
Just Enough Items: 4.14.4.267

Thank's
Fireztonez

**Comment by kindlich** [comment]
That was already in CrT by the time you asked, but now it's also documented ^^
<https://docs.blamejared.com/1.12//en/#Vanilla/Items/Tooltips/#removing-specific-tooltips>

**Comment by vizthex123** [comment]
The link is [https://docs.blamejared.com/1.12/en/Vanilla/Items/Tooltips/](https://docs.blamejared.com/1.12/en/Vanilla/Items/Tooltips/) now.
