### ISSUE TITLE
[Suggestion] be able to make 2 different items into the same without oredict

### ISSUE THREAD

**Issue by mariodk** [CraftTweaker/CraftTweaker-Documentation#157]
hey im making a private modpack for me & some friends with some recipe changes and also
replace some Ores/Metals(that only 1 mod uses) into more common ones
like make silver alot more usefull and turn mekanism´s osmium & afew other mod´s metal into silver (via add silver to theirs oredict)

but than i came across matter overdrive´s recipes that use tritanium & Dilithium crystal that i wanted to turn into Redstone Repository´s ingot & gem
turns out matter overdrive mod dont have ore:Dilithium or ore:tritanium in its recipe but just use <matteroverdrive:tritanium_ingot> instead of <ore:ingotTritanium>
so even if i add  Redstone Repository´s ingot & gem to ore:Dilithium or ore:tritanium oredict it wont change the recipe at all so it can use both 
unless i manual change every single recipe in the mod

so i was wondering if a idea like this script code here: 
<redstonerepository:material:1> = <matteroverdrive:tritanium_ingot>
can be possible
aswell as "remove" <matteroverdrive:tritanium_ingot> mostly from the game(from JEI/recipe viewing) and make only use of <redstonerepository:material:1>
so all recipes with  <matteroverdrive:tritanium_ingot> use  <redstonerepository:material:1> now
(craftingtable, furnace, machines & etc.) instead of i have to manual change every recipes becuase a mod dont use oredict in its recipes 

same for oredict like 
<ore:ingotOsmium> = <ore:ingotsilver>
remove <ore:ingotOsmium>

so every recipe with <ore:ingotOsmium> got replaced to silver ingot and removed <ore:ingotOsmium> from showing in JEI/recipe viewer
so basicalled replaced Osmium ingots (& others osmium stuff) with Silver
even set the Osmium ingot item icon into like thermalfoundation´s silver ingot/name
to truely replace Osmium with Silver (same for Non oredict items ofc) so now every recipes with Osmium ingot now use Silver ingots too and a Renamed Osmium ingot to Silver ingot that use  thermalfoundation´s silver´s item icon
so Osmium ingot is basically gone(for the Non modpack maker´s point of view) 
aswell as some way to Mass rename items
like Replace every "Osmium" to "Silver" 
Osmium dust,ingot,block, everything is now named Silver dust,ingot,block
via afew line of codes in the script instead of codes for Every osmium thing 

im sure a idea like this can be used for more than my example too 
to turn 1 item(osmium) complety into a other item(Silver) via crafttweaker
and now that 1 item(osmium) 
can now be used everywhere where the other item(silver) is used and visa versa
while that 1 item(osmium) is named and looking like the other item(silver)

**Comment by jaredlll08** [comment]
I have absolutely no idea what you are asking.

Have you looked at `or` ingredients?
so like:
```zenscript
var item = <minecraft:dirt> | <minecraft:diamond>;
```

Will accept either dirt or diamond
