### ISSUE TITLE
Does IWorld has getBlock()?

### ISSUE THREAD

**Issue by wanybae** [CraftTweaker/CraftTweaker-Documentation#166]
I have a question. 

I am translating IBlock.md to Korean then just saw this sentence.
- Using the getBlock(x,y,z) on an IWorld.

I checked IWorld page but it does not have getBlock method.

Which one is right?

**Comment by kindlich** [comment]
Yes, that method exists:

<https://github.com/CraftTweaker/CraftTweaker/blob/bce864aca33463ef0001a758c41ba88cceb4914b/CraftTweaker2-API/src/main/java/crafttweaker/api/world/IWorld.java#L64>


If it's not described in the IWorld file, would you mind create a PR adding it?

**Comment by wanybae** [comment]
Ok, I'm gonna try to add it. :)

**Comment by kindlich** [comment]
I am closing this issue because the methods are indeed described in the IWorld file, below the table:

<https://docs.blamejared.com/ko/#Vanilla/World/IWorld/#get-block-at-specific-position>
