### ISSUE TITLE
problem with documentation for immersive engineering

### ISSUE THREAD

**Issue by fireair** [CraftTweaker/CraftTweaker-Documentation#169]
I have been trying to add custom minerals and the documentation doesn't seem to be correct.
here what i have
import mods.immersiveengineering.Excavator;

mods.immersiveengineering.Excavator.addMineral("Africite", 50, 0.0005, ["ore:orevibranium", "ore:oreDiamond","ore:orepalladium","ore:oreTitanium"], [35, 15, 25, 25]);
i also tried the ore dictionary names
which didnt work

**Comment by kindlich** [comment]
As far as I know you either use the item, so `mod:item` or the ore dictionary directly, so `oreDiamond`

**Comment by kindlich** [comment]
Is this still an issue?

**Comment by kindlich** [comment]
Closing this because no answer received.
If this is still an issue, please respond here and I will reopen this issue.
