### ISSUE TITLE
Setting amount for output stack

### ISSUE THREAD

**Issue by PrincessRTFM** [CraftTweaker/CraftTweaker-Documentation#178]
The wiki lists two different methods under `IItemStack` amounts - `.amount(int amount)` and `.withAmount(int amount)` - but doesn't explain the difference (is there one?) between them. The "returns" line only reads `A new IItemStack with the changed property`. In (much) older version, I recall that one of them was for an input filter and one was to set an output stack's quantity, is this still true or are they now equivalent?

**Comment by kindlich** [comment]
Originally, `.withAmount` was called when using the  `*` Operator.
`.amount` was the alternative way of calling the method.

With changes in ZS both annotations could be used on one method so now they still do the same, they create a new IItemStack object with the new stack size.

**Comment by kindlich** [comment]
Closing this issue as no further questions were asked.
If this is incorrect, please reply to this issue and it will be reopened.
