### ISSUE TITLE
[ModTweaker] Compactor modes for Thermal Expansion are outdated

### ISSUE THREAD

**Issue by Zangdorx** [CraftTweaker/CraftTweaker-Documentation#185]
Compactor modes should be changed to the new system that allows either ALL, PLATE, COIN, or GEAR.

**Comment by kindlich** [comment]
The compactor has 4 add/remove methods:
```
press
mint
storage
gear
```

That were the old names for (in order)
```
ALL
COIN
PLATE
GEAR
```
