### ISSUE TITLE
Incorrect links in Wiki for Artisan Worktables

### ISSUE THREAD

**Issue by DWX12** [CraftTweaker/CraftTweaker-Documentation#186]
#### What happens:
The links listed for Artisan Worktables are for the Advanced Mortar mod instead.

Artisan Worktables
Information:

Artisan Worktables adds a wide arrangement of custom Crafting Tables that requires “Tools” for the Crafting Process. This mod has both JEI and GameStages support, as well as quite robust CraftTweaker Integration!
For More Information:

https://minecraft.curseforge.com/projects/advanced-mortars
Bug Reports:

https://github.com/codetaylor/advancedmortars/issues

#### What you expected to happen:
The links should be for Artisan Worktables and not Advanced Mortars.

https://minecraft.curseforge.com/projects/artisan-worktables

https://github.com/codetaylor/artisan-worktables/issues

[pastebin/gist/etc link here]
https://crafttweaker.readthedocs.io/en/latest/#Mods/Artisan_Worktables/Artisan_Worktables/

**Comment by kindlich** [comment]
Moved issue to the wiki repository
