### ISSUE TITLE
[Addition] Thermal Expansion recipes

### ISSUE THREAD

**Issue by GreatestFool** [CraftTweaker/CraftTweaker-Documentation#188]
I don't use github enough to reliably make a pull request or whatever it's called, so I'll simply do it like this instead.

Talked with jaredlll08 for an [issue I was having](https://github.com/jaredlll08/ModTweaker/issues/727) with TE using modtweaker. The issue isn't really important, rather the solution.

> Thermal expansion uses remove by input, not remove by output, so removing the coin won't do anything, as the recipe doesn't exist.

Please add a note or something to the TE entries of the Modtweaker section in the CraftTweaker docs, that the recipes work by removing inputs, not outputs.

**Comment by kindlich** [comment]
All ThermalExpansion handlers remove by input.
This can be seen in the method signature:
```
mods.thermalexpansion.Compactor.removeMintRecipe(IItemStack input);
```


If you really want to create a PR you can try and follow the steps on the docs page:
<https://docs.blamejared.com/en/#Contribute/SetupGithub/>

Start with that page and then follow the link to "use the online Editor" and after that "file a PR"

**Comment by GreatestFool** [comment]
I see, I didn't realize. Thanks for pointing it out. If I have the time to do a pull request, I'll follow the guide you linked to.
