### ISSUE TITLE
The example of removing recipes from machines GregTech CE does not work.

### ISSUE THREAD

**Issue by Drive3d** [CraftTweaker/CraftTweaker-Documentation#196]
Hi! does not work example removing.
https://crafttweaker.readthedocs.io/en/latest/#Mods/GregTechCE/Machines/#removing

import mods.gregtech.recipe.RecipeMap;
val compressor as RecipeMap = RecipeMap.getByName("compressor");
compressor.findRecipe(2, [<<minecraft:redstone>>], null).remove();

[INITIALIZATION][CLIENT][ERROR] [crafttweaker]: Error executing {[0:crafttweaker]: Delete.zs}: null

**Comment by Drive3d** [comment]
In other examples I found null -> [null]. But this recipe still can not be removed.
Example that works:
import mods.gregtech.recipe.RecipeMap;
val Assembler = RecipeMap.getByName("assembler");
Assembler.findRecipe(400,[<minecraft:redstone>,<minecraft:stick>],[null]).remove();
Assembler.findRecipe(1600,[<gregtech:meta_item_1:12071>*2,<minecraft:redstone>],[null]).remove();

**Comment by Drive3d** [comment]
<

**Comment by kindlich** [comment]
@NanamiArihara 

Sorry for the ping but you were the one who added these wiki entries.
I don't know the GTCE crt support, but is what he is saying correct?

**Comment by Drive3d** [comment]
I don't speak English well. And poorly understood question.
The example you have doesn't work.
https://crafttweaker.readthedocs.io/en/latest/#Mods/GregTechCE/Machines/#removing

**Comment by NanamiArihara** [comment]
Sure it is a pretty old documentation, and even need to be rework
________________________________
