### ISSUE TITLE
Advanced recipie NBT append or replace

### ISSUE THREAD

**Issue by 0xebjc** [CraftTweaker/CraftTweaker-Documentation#198]
If you already have this feature and I missed it, I apologize.   I am trying to define crafting recipes that either replaces or append NBT data from one of the input items to the output.

Example:
recipe.addShapeless(<minecraft:diamond_sword>.appendTag(allEnchanments), 
    [<minacraft:golden_sword>.withTag(allEnchantments), <minecraft:diamond_block>]);

recipe.addShaped(<minecraft:diamond_sword>.replaceTag(allEnchanments(1,1)), 
    [null, null, null],
    [null, <minacraft:golden_sword>.withTag(allEnchantments), <minecraft:diamond_block>],
    [null, null, null]
    ]);

Where the (1,1) is the row and column of the crafting table counting [0-2 x 0-2] rows & columns.

**Comment by 0xebjc** [comment]
would be nice if rocky tweaks anvil recipes supported this also.

**Comment by kindlich** [comment]
That is already possible in the form of recipe functions:
<https://docs.blamejared.com/en/#Vanilla/Recipes/Crafting/Recipe_Functions/>

You can see an example in here:
<https://github.com/CraftTweaker/CraftTweaker-Examples/blob/master/crafttweaker/crafting%20table%20recipes/recipe%20functions/enchantment_transfer/enchantment_transfer.zs>
