### ISSUE TITLE
No member `recipestages` in mods

### ISSUE THREAD

**Issue by FedoraGameDev** [CraftTweaker/CraftTweaker-Documentation#203]
I've been struggling with this for some time. Below is my code, and Minecraft keeps telling me recipestages does not exist in mods. I'm running Minecraft 1.12.2 with forge 14.23.5.2837.

```
import crafttweaker.item.IItemStack;
import mods.jei.JEI;

val craftingLevels = {
    "blacksmith_1" : [
        <minecraft:iron_sword>,
        <minecraft:iron_pickaxe>,
        <minecraft:iron_axe>,
        <minecraft:iron_hoe>,
        <minecraft:iron_shovel>,
        <minecraft:iron_boots>,
        <minecraft:iron_leggings>,
        <minecraft:iron_chestplate>,
        <minecraft:iron_helmet>,
    ] as IItemStack[]
} as IItemStack[][string];

for level in craftingLevels
{
    for recipe in craftingLevels[level]
    {
        mods.recipestages.Recipes.setRecipeStage(level, recipe);
    }
}
```

**Comment by jaredlll08** [comment]
Wrong repo.

You do have REcipe stages installed right?

**Comment by FedoraGameDev** [comment]
Oh woops, didn't realize. My mistake.

I do have GameStages 1.12.2-2.0.115 in the game, which is what the documentation references.

**Comment by FedoraGameDev** [comment]
Ah. There's a second mod. My mistake again.

**Comment by jaredlll08** [comment]
![image](https://user-images.githubusercontent.com/5553605/62834392-ce3a3100-bc4b-11e9-84bf-74b0582dea5a.png)

https://www.curseforge.com/minecraft/mc-mods/recipe-stages
