### ISSUE TITLE
Trouble with zs files

### ISSUE THREAD

**Issue by SonshineBoys** [CraftTweaker/CraftTweaker-Documentation#215]
I had some trouble with your discord server, and so I just wanted to know how to make a zs file. There doesn't seem to be any major code-based services that let me make them that are not worth money. What are other people using?

**Comment by jaredlll08** [comment]
Just make a file with a .zs extension...?

**Comment by SonshineBoys** [comment]
I'm asking what system you use to make one
It can't just appear from nothing

**Comment by jaredlll08** [comment]
Any text editor of you choice.

Read the docs on the part about writing scripts
https://docs.blamejared.com/1.12/en/#Getting_Started/#writing-your-first-script

**Comment by SonshineBoys** [comment]
What would it mean if it says the following?
I made a small file that just talks about removing bone meal's recipes but it doesn't seem to work like I thought it did
![Untitled99](https://user-images.githubusercontent.com/56801575/67167284-39436a80-f355-11e9-84d1-f060f22f75fe.png)

**Comment by jaredlll08** [comment]
As the issue template says, this repository is for issues with the documentation.


I suggest you join https://discord.blamejared.com
To get some help with scripting.

**Comment by SonshineBoys** [comment]
The discord doesn't work for me it says I cannot message because of privacy.
And I don't understand discord at all...

**Comment by SonshineBoys** [comment]
_Your message could not be delivered because you don't share a server with the recipient or you disabled direct messages on your shared server, recipient is only accepting direct messages from friends, or you were blocked by the recipient._
Thats what it says.

**Comment by jaredlll08** [comment]
That is for sending some one a private message, the link I gave to a server, which you can ask questions in.

**Comment by SonshineBoys** [comment]
![image](https://user-images.githubusercontent.com/56801575/67167478-9b9d6a80-f357-11e9-927a-b8d3e476f6c8.png)
Sorry about all this messaging...
