### ISSUE TITLE
No rule against publicly sharing zs scripts?

### ISSUE THREAD

**Issue by in-tension** [CraftTweaker/CraftTweaker-Documentation#230]
I'm not sure this is the right place to ask this, but I wanted to double check before I do that it's okay for me to post zs files on github in my own public repo, of course with links to crafttweaker.

**Comment by jaredlll08** [comment]
Uh, I can't control what you do with your scripts.

Just know that normal licensing rules apply, so if you're taking scripts from other people, you need to be wary of that

**Comment by in-tension** [comment]
great, cool, thanks

**Comment by CrankySupertoon** [comment]
Think about if this way if you make a Java class it’s your class you can do what you want with it. If it’s **your** zenscript file there is nothing we can do for you to not post it, I mean why would we stop you
