### ISSUE TITLE
ModTweaker Thaumcraft SalisMundus Blockstate Error with Artisan Worktables

### ISSUE THREAD

**Issue by BranTuna** [CraftTweaker/CraftTweaker-Documentation#233]
### Problem
This may be a simple coding error, but I'm having trouble finding out how to get the **IBlock** _blockstate_ correct for converting a _Basic Artisans Worktable/Workstation/Workshop_ into their respective _Artisans Magic Worktable/Workstation/Workshop_ using the **SalisMundus** handler.

_It errors._

### Details
**Here's the Code:**
`import mods.thaumcraft.SalisMundus;
SalisMundus.addSingleConversion(<blockstate:artisanworktables:worktable:5>.block, <artisanworktables:worktable:7>);
SalisMundus.addSingleConversion(<blockstate:artisanworktables:workstation:5>.block, <artisanworktables:workstation:7>);
SalisMundus.addSingleConversion(<blockstate:artisanworktables:workshop:5>.block, <artisanworktables:workshop:7>);`

_Please Help me._

**Comment by kindlich** [comment]
We'll need a little more info than `it errors`.
Please upload your crafttweaker.log file to either gist.github.com or pastebin or another similar service and provide a link here.

**Comment by BranTuna** [comment]
> [INITIALIZATION][CLIENT][WARNING] Invalid blockstate property format '5'. Using default property value.
> [INITIALIZATION][CLIENT][WARNING] Invalid blockstate property format '5'. Using default property value.
> [INITIALIZATION][CLIENT][WARNING] Invalid blockstate property format '5'. Using default property value.

**Comment by kindlich** [comment]
The format for blockstate Bracket Handlers is different:

See the wiki entry:
<https://docs.blamejared.com/1.12/en/#Vanilla/Brackets/Bracket_BlockState/#examples>
```
//block of dirt
<blockstate:minecraft:dirt>

//oak log, vertical
<blockstate:minecraft:log>
<blockstate:minecraft:log:variant=oak,axis=y>

//spruce log, horizontal along the x-axis
<blockstate:minecraft:log:variant=spruce,axis=x>
```

Blockstates themselves don't have meta values, you need to find their property name and use that.
