### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by Wolfseverest93** [CraftTweaker/CraftTweaker-Documentation#235]
It would appear that you removed, or otherwise may have damaged the function import process, as every attempt at using it has resulted in it being called out with the ever so lovely "[23:48:41] [Client thread/INFO] [minecraft/GuiNewChat]: [CHAT] ERROR: b02recipeRemoval.zs:4 > Not a valid type"

Whereas these are the first five lines of the file in question *mind the edit to fight against automatic markdown
(insertpoundsymbolhere)priority 1

(insertpoundsymolhere) Functions
import recipes.removeByRecipeName as r;
import mods.jei.JEI.hide as h;

So I ask, should I instead replace the import call with either static or global, or are these calls also broken?

**Comment by kindlich** [comment]
Since you did not specify your MC version I am going to assume MC 1.12.

`recipes` is a global field, so you cannot import it.
