### ISSUE TITLE
Landing page is broken in Firefox

### ISSUE THREAD

**Issue by DBotThePony** [CraftTweaker/CraftTweaker-Documentation#266]
![firefox_hMB6V6tY2K](https://user-images.githubusercontent.com/6339511/78450528-58d31300-76a9-11ea-82aa-efb910ec2010.png)
![firefox_yw5wPVC4u7](https://user-images.githubusercontent.com/6339511/78450529-5a9cd680-76a9-11ea-828c-beb87959eb34.png)

Cause: you use `defer` tag on `jquery` javascript in `head`, but use `async` for script inside `body`.
`defer` tells the browser to load the script in parallel, but not to execute it until everything else is loaded.
`async` tells the browser to load the script in parallel and execute it in place regardless whenever other scripts/DOM are/is finished loading or not

*landing page is effectively chrome-only, chrome is new IE confirmed*

https://flaviocopes.com/javascript-async-defer/

**Comment by jaredlll08** [comment]
Thanks, this should have been fixed :)
