### ISSUE TITLE
BlockPlaceEvent has no isPlayer

### ISSUE THREAD

**Issue by twothe** [CraftTweaker/CraftTweaker-Documentation#287]
The documentation on the 1.12 [BlockPlaceEvent](https://docs.blamejared.com/1.12/en/Vanilla/Events/Events/BlockPlace/) says there is a `isPlayer` field, but that [actually doesn't exist](https://github.com/CraftTweaker/CraftTweaker/blob/1.12/CraftTweaker2-API/src/main/java/crafttweaker/api/event/BlockPlaceEvent.java).

**Comment by jaredlll08** [comment]
Seems more like an issue with the docs than the mod
