### ISSUE TITLE
Incorrect documentation for ExnihiloCreatio

### ISSUE THREAD

**Issue by LewisSaber** [CraftTweaker/CraftTweaker-Documentation#289]
In documentation if you go Mods -> Ex Nihilo Creatio -> Sieving -> Removal
there is mods.exnihilocreation.Sieve.removeAll(); - > 
exnihilocreation while should be exnihilocreatio(without last n)

**Comment by LewisSaber** [comment]
Just found out same mistake in Crucible heat sources(adding and removing recipes),crooking removing line include same mistake

**Comment by CrankySupertoon** [comment]
Dang it
