### ISSUE TITLE
Custom Inspirations cauldron recipes don't work

### ISSUE THREAD

**Issue by darthvader45** [CraftTweaker/CraftTweaker-Documentation#322]
I try to add custom recipes using the examples provided on the wiki, yet it seems I get "bad type on operand stack" errors.  Seems like the format changed or something.  Can you provide a 1.12.2 example that should work?

**Comment by jaredlll08** [comment]
What is your actual script that you are trying?

**Comment by darthvader45** [comment]
Nvm, turns out I was stupid and didn't have Modtweaker.  I was using a modified version of the script from the Skyfactory files.
