### ISSUE TITLE
Documentation request: adding smithing table recipes

### ISSUE THREAD

**Issue by nepphhh** [CraftTweaker/CraftTweaker-Documentation#325]
I see from commit c49f5ad36aab9b1433f7536eb5a1a33c840bb706 that smithing table support was recently added. What's the syntax for adding/modifying smithing table recipes?

**Comment by jaredlll08** [comment]
https://docs.blamejared.com/1.16/en/vanilla/api/managers/SmithingManager/#g-addrecipe
