### ISSUE TITLE
mc1.16.1|ct12.0.4| Im creating a pack. i cant get anything to work besed on the reference materials ive found.

### ISSUE THREAD

**Issue by reapersremorse** [CraftTweaker/CraftTweaker-Documentation#329]
I am able to add and remove anything from vanilla crafting. but when i try anything modded it does not work. the chat error complains about syntax. I can't change fuel values, hide items in jei, and maybe more. 
I'm able to add and remove recipes for vanilla and for the extended crafting mod easily. but when I try doing something "extra" it does not work.
if anyone can show me the error in my ways, I would be most appreciated.
if i need to setup a github repo, i will.

this is a personal pack that i have not released, mostly used for me and some friends. im in the process of rebuilding for the 5th version

-----------------------------------------------------------------------------------------------------

my referenced material: 
https://docs.blamejared.com/
https://github.com/CraftTweaker/CraftTweaker-Examples/blob/master/1.14/general.zs
https://github.com/CraftTweaker/CraftTweaker-Documentation/blob/master/docs/Mods/JEI/JEI.md

-----------------------------------------------------------------------------------------------------

Important info:
Minecraft 1.16.1
forge-32.0.108
CraftTweaker | Jaredlll08 | CraftTweaker-1.16.1-7.0.0.24.jar
Crafting Tweaks | BlayTheNinth | CraftingTweaks_1.16.1-12.0.4.jar
Applied Energistics 2 | AlgorithmX2 | appliedenergistics2-8.0.0-beta.2.jar
JEI Integration | SnowShock35 | jeiintegration_1.16.1-4.0.0.4.jar
JEITweaker | Jaredlll08 | JEITweaker-1.16.1-1.0.1.2.jar
Just Enough Items (JEI) | mezz | jei-1.16.1-7.0.1.10.jar
Just Enough Resources (JER) | way2muchnoise | JustEnoughResources-1.16.1-0.11.1.98.jar
KubeJS | LatvianModder | kubejs-2.7.2.59.jar
Extended Crafting | BlakeBr0 | ExtendedCrafting-1.16.1-3.0.1.jar

-----------------------------------------------------------------------------------------------------

//my furnace_changes.zs file
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.item.IIngredient;
import crafttweaker.api.FurnaceManager;
import crafttweaker.api.registries.ICookingRecipeManager;
import crafttweaker.api.BlastFurnaceManager;
import crafttweaker.api.CampFireManager;
import crafttweaker.api.CraftingTableManager;
import crafttweaker.api.registries.IRecipeManager;
import crafttweaker.api.SmokerManager;
import crafttweaker.api.StoneCutterManager;

furnace.setFuel(<minecraft:glass>, 400); //wont work
mods.jei.JEI.hideCategory("appliedenergistics2:facade");//wont work
mods.jei.JEI.removeAndHide(<appliedenergistics2:facade>);//wont work
mods.jei.JEI.hide(<item:appliedenergistics2:facade>);//wont work

-----------------------------------------------------------------------------------------------------

//my remove_recipes.zs file
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.item.IIngredient;
import crafttweaker.api.FurnaceManager;
import crafttweaker.api.registries.ICookingRecipeManager;
import crafttweaker.api.BlastFurnaceManager;
import crafttweaker.api.CampFireManager;
import crafttweaker.api.CraftingTableManager;
import crafttweaker.api.registries.IRecipeManager;
import crafttweaker.api.SmokerManager;
import crafttweaker.api.StoneCutterManager;

//removeRecipe(IItemStack output);
craftingTable.removeRecipe(<item:quark:charcoal_block>);//this works well

-----------------------------------------------------------------------------------------------------
//logs
[crafttweaker.log](https://github.com/CraftTweaker/CraftTweaker-Documentation/files/5189927/crafttweaker.log)
[latest.log](https://github.com/CraftTweaker/CraftTweaker-Documentation/files/5189928/latest.log)

**Comment by jaredlll08** [comment]
report here:
https://github.com/CraftTweaker/CraftTweaker/issues
and follow the template there (including uploading the scripts to https://gist.github.com
