### ISSUE TITLE
Ticking block entity error with tinker's complement high oven, custom heat recipes. MC1.12.2

### ISSUE THREAD

**Issue by Squatlock** [CraftTweaker/CraftTweaker-Documentation#352]
Hello, I was trying to configure heat recipes using crafttweaker for the high oven, but whenever I test it in game I get this error.

The game crashed whilst ticking block entity
Error: java.lang.ArithmeticException: / by zero
Exit Code: -1

The script I was using is 

mods.tcomplement.highoven.HighOven.addHeatRecipe(<liquid:steam> * 3, <liquid:water>, 347);

It also crashed when I tried this script

mods.tcomplement.highoven.HighOven.addHeatRecipe(<liquid:gold>, <liquid:tin>, 347);

If you need more information here is the link to my reddit post https://www.reddit.com/r/feedthebeast/comments/j9hbz0/crafttweaker_high_oven_help/

**Comment by jaredlll08** [comment]
wrong repo, report to the modtweaker repo, and provide your full script and logs on pastebin.
