### ISSUE TITLE
custom recipes dont work

### ISSUE THREAD

**Issue by fleXXo22** [CraftTweaker/CraftTweaker-Documentation#368]
all of my custom recipes arent working anymore. They worked yesterday, but now the dont work. What can i do? the mod gives me only the ingame error code:  ERROR: [crafttweaker]: Error executing {[0:crafttweaker]:all.zs}: null

can you help me?
[all.txt](https://github.com/CraftTweaker/CraftTweaker-Documentation/files/5509924/all.txt)

**Comment by jaredlll08** [comment]
report to https://github.com/CraftTweaker/CraftTweaker and follow the template there
