### ISSUE TITLE
1.15.2 Event documentation needs clarification

### ISSUE THREAD

**Issue by ah-OOG-ah** [CraftTweaker/CraftTweaker-Documentation#386]
The documentation for all events in the 1.15.2 wiki is poor, as it does not explain how to actually use the events. This could be fixed by either documenting CTEventManager or, as a temporary fix, adding a screenshot/paste of [this](https://discord.com/channels/136877912698650625/354745056743260172/779013713478680627) discord message clarifying event use.

**Comment by jaredlll08** [comment]
As it stands, 1.15 is no longer supported.

The 1.16 version of the page does have updated information though.
https://docs.blamejared.com/1.16/en/vanilla/api/event/CTEventManager/
