### ISSUE TITLE
IE Metal Press

### ISSUE THREAD

**Issue by octaarium** [CraftTweaker/CraftTweaker-Documentation#391]
I tried to add Immersive Engineerin Metal Press recipe like shown on CT Documentation but CT Log outputs: 
[17:48:59.884][DONE][CLIENT][ERROR] metal_press.zs:5:0 No such member: addRecipe
 
Here is the script:

import crafttweaker.api.item.IItemStack;
import crafttweaker.api.registries.IRecipeManager;

<recipetype:immersiveengineering:metal_press>.addRecipe("copy_manual", <item:minecraft:paper>, <item:immersiveengineering:manual>, 1000, <item:immersiveengineering:manual>);

It's exactly as shown on https://docs.blamejared.com/1.16/en/mods/ImmersiveEngineering/MetalPress/
Is thsi a bug or am I missing something.

[crafttweaker.log](https://github.com/CraftTweaker/CraftTweaker-Documentation/files/5912499/crafttweaker.log)

**Comment by jaredlll08** [comment]
Report to https://github.com/CraftTweaker/CraftTweaker/issues
and follow the issue template there.
