### ISSUE TITLE
[1.12.2] Typo in IServer Docs Page or IServer.java ?

### ISSUE THREAD

**Issue by pjc21** [CraftTweaker/CraftTweaker-Documentation#399]
When trying to use server.isOP(player); as shown in the docs [IServer](https://docs.blamejared.com/1.12/en/Vanilla/Game/IServer/) page,  I keep getting error No such member: isOP in crafttweaker.server.IServer.  

Upon checking the IServer.java I found the issue, it's a lowercase 'p' isOp in [IServer.java](https://github.com/CraftTweaker/CraftTweaker/blob/1.12/CraftTweaker2-API/src/main/java/crafttweaker/api/server/IServer.java)

Not sure if this is a typo in the docs or IServer.java, just wanted to let you know.

Thanks

**Comment by jaredlll08** [comment]
https://github.com/CraftTweaker/CraftTweaker-Documentation/commit/8832de4e369b494f3beb84c45ee8ae08a84ef562
