### ISSUE TITLE
Thermal Expansion Dynamos have misleading documentation

### ISSUE THREAD

**Issue by Pacca64** [CraftTweaker/CraftTweaker-Documentation#410]
Every documentation page for Modtweakers' Thermal Expansion dynamo support offers invalid examples. Every page uses 13 as an example for the energy output of the dynamo. However, each dynamo has a limited range of energy it can support, and ALL of them are unable to generate energy in the double digits. Their limits are as follows:

```Compression:
energy < 10000 || energy > 200000000

Enervation:
energy < 2000 || energy > 200000000

Magmatic:
energy < 10000 || energy > 200000000

Numistic:
energy < 2000 || energy > 200000000

Reactant:
energy < 10000 || energy > 200000000

Steam:
energy < 2000 || energy > 200000000
```

Making the examples use valid energy values and including the minimum and maximum energy limits in the documentation would save a lot of confusion.

**Comment by democat3457** [comment]
(btw code blocks are triple backticks [\`\`\`])
