### ISSUE TITLE
I found a grammatical error on the wiki

### ISSUE THREAD

**Issue by JadianRadiator** [CraftTweaker/CraftTweaker-Documentation#426]
I found a grammatical error on the wiki
https://docs.blamejared.com/1.16/en/mods/contenttweaker/SimpleWalkthrough/
First copy/paste example comment on the pillar type uses "axes" where it should have used "axis" since it's talking about the rotation of the block.

**Comment by democat3457** [comment]
as discussed in the discord, not a grammar error because `axes` is also plural `axis`
