### ISSUE TITLE
ClientWorld can not be cast to ServerWorld

### ISSUE THREAD

**Issue by kd8lvt** [CraftTweaker/CraftTweaker-Documentation#432]
Trying to use `MCWorld.asServerWorld()` results in an instant crash. If you need any more info I'd be happy to give it :)

crafttweaker.log and scripts
[https://gist.github.com/kd8lvt/2a5676f5ce446b5f2c76a539fb924fd4](https://gist.github.com/kd8lvt/2a5676f5ce446b5f2c76a539fb924fd4)

latest.log
[https://gist.github.com/kd8lvt/020397be1f9be357dc2b03e7d46c0281](https://gist.github.com/kd8lvt/020397be1f9be357dc2b03e7d46c0281)

Mod Versions:
forge-36.1.0
CraftTweaker-1.16.5-7.1.0.313
ContentTweaker-1.16-1.0.0.develop.19

**Comment by jaredlll08** [comment]
Firstly this is the wrong repo for issues.

Secondly of course trying to cast it to a server world on the client thread is going to crash, you need to check if the world is not remote first:
https://docs.blamejared.com/1.16/en/vanilla/api/world/MCWorld/#g-isremote

```
remote == true if it is the client thread
remote == false if it is the server thread
```

**Comment by kd8lvt** [comment]
my bad, sorry about the inconvenience. thanks for the help

**Comment by jaredlll08** [comment]
No problem, it wasn't an inconvenience :)
