### ISSUE TITLE
1.16 wiki API package error

### ISSUE THREAD

**Issue by MakesYT** [CraftTweaker/CraftTweaker-Documentation#434]
In the wiki 
![image](https://user-images.githubusercontent.com/42534870/121043976-b603b080-c7e7-11eb-92cb-587dfefd4abe.png)
but in fact it is "crafttweaker.api.blocks.MCBlock"
The lack of the s

**Comment by jaredlll08** [comment]
Where?

**Comment by MakesYT** [comment]
All the places used, this is an example
https://docs.blamejared.com/1.16/zh/vanilla/api/blocks/MCBlockState/

**Comment by MakesYT** [comment]
only in zh?

**Comment by Witixin1512** [comment]
If your issue is that the Docs subfolder doesn't match the actual package the ZenClass is on, yeah, that's not an issue.
They don't need to match and they don't here :P 
They also don't match in other locales that I can see. 
If there isn't anything else, this can be closed imo.
