### ISSUE TITLE
Fluid Sieving Machine from Industrial Foregoing support (1.12.2)

### ISSUE THREAD

**Issue by v1993** [CraftTweaker/CraftTweaker-Documentation#437]
It would be nice to have support for Fluid Sieving Machine from Industrial Foregoing mod. It even appears that support for it actually existed in older versions (I found some outdated docs describing interface) but was dropped/not reimplemented later on.

**Comment by jaredlll08** [comment]
We don't add support for that mod, you would need to ask whatever mod does to add it.

**Comment by v1993** [comment]
Ahh, turns out I suck at reading. Well, thanks!
