### ISSUE TITLE
mod Create syntax question SequencedAssemblyRecipeBuilder

### ISSUE THREAD

**Issue by ptk2003** [CraftTweaker/CraftTweaker-Documentation#464]
example from https://docs.blamejared.com/1.16/en/mods/Create/SequencedAssembly/

<recipetype:create:sequenced_assembly>.registerRecipe("seq_test", (rb) => {
    rb.transitionTo(<item:minecraft:glass>);
    rb.require(<item:minecraft:arrow>);
    rb.loops(2);
    rb.addOutput(<item:minecraft:diamond>, 1);
    rb.addOutput(<item:minecraft:apple>, 1);
    rb.addStep(<recipetype:create:cutting>.factory(), (rb1) => rb1.duration(50));
    rb.addStep(<recipetype:create:pressing>.factory(), (rb1) => rb1.duration(500));
    rb.addStep(<recipetype:create:deploying>.factory(), (rb1) => rb1.require(<item:minecraft:dirt>));
});

/ct format got an error: [ERROR] Error running scripts: Invalid statement
if I commented all addStep - no error (no 1 of 3 addStep above not pass /ct format)

1.16.5-forge-36.2.2
CraftTweaker-1.16.5-7.1.2.411
CreateTweaker-1.0.0.20
create-mc1.16.5_v0.3.2d

**Comment by jaredlll08** [comment]
I need to update the docs.

This should work:
```zenscript
var builder = <recipetype:create:sequenced_assembly>.builder("seq_test")
    .transitionTo(<item:minecraft:glass>)
    .require(<item:minecraft:arrow>)
    .loops(2)
    .addOutput(<item:minecraft:diamond>, 1)
    .addOutput(<item:minecraft:apple>, 1)
    .addStep(<recipetype:create:cutting>.factory(), (rb) => rb.duration(50))
    .addStep(<recipetype:create:pressing>.factory(), (rb) => rb.duration(500))
    .addStep(<recipetype:create:deploying>.factory(), (rb) => rb.require(<item:minecraft:dirt>));

<recipetype:create:sequenced_assembly>.addRecipe(builder);
```

**Comment by ptk2003** [comment]
Now addStep not pass /ct format with [ERROR] Error running scripts: Not yet implemented! (if i remove all .addStep(* - /ct format ok)

**Comment by jaredlll08** [comment]
As it currently stands, `/ct format` is not production usable, any any errors related to it are not going to be resolved.

Does the script error when `/reload` is used?

**Comment by ptk2003** [comment]
the /reload works without error and the recipe is applied. 
works fine.
thank you.
