### ISSUE TITLE
Example Script to remove ingredient from all recipes?

### ISSUE THREAD

**Issue by Boolyman** [CraftTweaker/CraftTweaker-Documentation#476]
Hello.

I looked through the documentation on your wiki but could not find a specific example of this. 

I want to do something such as replace Iron Ingots with Silver ingots for all "XXX.mod" recipes.  I have tried unsuccessfully a few times, but to no avail.  Could you give me an example script of how one would do this?

**Comment by Boolyman** [comment]
1.16.5

**Comment by jaredlll08** [comment]
```zenscript
import crafttweaker.api.recipe.Replacer;

Replacer.forMods("create").replace(<item:minecraft:string>, <item:minecraft:diamond>).execute();
```

That script will replace string with diamonds in all recipes from `create`.

Is that what you want?
