### ISSUE TITLE
Support for Anvil recipes?

### ISSUE THREAD

**Issue by Robert-DeForrest-Reynolds** [CraftTweaker/CraftTweaker-Documentation#478]

**Comment by jaredlll08** [comment]
There is no such thing as anvil recipes.

The anvil uses an event system, so for example, to "remove" an anvil recipe, you can do:

```zenscript
CTEventManager.register<MCAnvilUpdateEvent>(event => {
    if <item:minecraft:diamond_sword>.matches(event.left)
        event.cancel();
});
```

Which will remove any anvil thing with a diamond sword in the left slot.

You can read more about the event here
https://docs.blamejared.com/1.16/en/vanilla/api/event/MCAnvilUpdateEvent/

And if you need any help with it, you can ask here:
https://discord.blamejared.com
