### ISSUE TITLE
Documentation on Arrays?

### ISSUE THREAD

**Issue by EliteKlopapier** [CraftTweaker/CraftTweaker-Documentation#482]
Arrays are not documented for 1.16 and the instructions from the 1.12 documentation (specifically adding a new element to an array) don't seem to work in 1.16. I think arrays are very important so I would really appreciate them being documented. Thanks in advance!

**Comment by kindlich** [comment]
Can you check if the description in here is missing something for you?
<https://github.com/CraftTweaker/CraftTweaker-Documentation/pull/485/files?short_path=9bb461a#diff-9bb461a400250ee7df9581c8b0a902e0d4f1497e82f48a532cec5dfb2eb85337>

**Comment by EliteKlopapier** [comment]
Sorry for bothering you, but I tried to follow the new documentation on arrays and lists and anything containing "= new" seems to be counted as invalid. Any ideas? Thanks.

**Comment by kindlich** [comment]
What exactly did you try (i.e. what is your script and error meassages)?
The calls in the `Creating a List or an Array` are stubs, the names in capital letters need to be filled in with the proper types, e.g. `string`.

**Comment by EliteKlopapier** [comment]
Context: I want to add the cooking recipes from Farmer's Delight to Create's mixer. The "ingredients" property of the recipes from getAllRecipes() is a List of the type IIngredient and the mixer needs an array of IIngredientWithAmount. My idea was to make a new List, fill it with the ingredients.asIIngredientWithAmount() and convert it to an array. Here's the code for that:

`
for recipe in <recipeType:farmersdelight:cooking>.getAllRecipes()
{
	val ingr = new List<IIngredientWithAmount>();
	for ingredient in recipe.ingredients
	{
		ingr.add(ingredient.asIIngredientWithAmount());
	}
	val ingredients = ingr as IIngredientWithAmount[];
	
	<recipetype:create:mixing>.addRecipe(recipe.id, "heated", recipe.output, ingredients, [<fluid:minecraft:water>* 1000], 100);
}
`

The highlighter underlines List, saying it instead #expected [DOT], [IDENTIFIER], [DOT2] etc. The error message for that line is just "No compatible methods found".

**Comment by kindlich** [comment]
Did you import IIngredientWithAmount and List?

**Comment by EliteKlopapier** [comment]
Is this the correct way to import them?
```
import crafttweaker.api.item.IIngredientWithAmount;
import stdlib.List;
```

**Comment by jaredlll08** [comment]
> The highlighter underlines "List", saying it instead expected [DOT], [IDENTIFIER], [DOT2] etc. The error message for that line is just "No compatible methods found".

Just to confirm @EliteKlopapier are you actually running the game?

We don't have a highlighter that does syntax checking, and the only syntax checker plugin that exists only works for 1.12 syntax (afaik).

The following script works for me:
```zenscript
import crafttweaker.api.item.IIngredientWithAmount;
import stdlib.List;

for recipe in furnace.getAllRecipes()
{
	val ingr = new List<IIngredientWithAmount>();
	for ingredient in recipe.ingredients
	{
		ingr.add(ingredient.asIIngredientWithAmount());
	}
	val ingredients = ingr as IIngredientWithAmount[];

}
```


Just a note with your script though, you have:
```zenscript
<recipeType:farmersdelight:cooking>
```
which is invalid. It should be:
```zenscript
<recipetype:farmersdelight:cooking>
```
with a lowercase `T` in `recipetype`
