### ISSUE TITLE
Craft Tweaker error

### ISSUE THREAD

**Issue by 44Cal3b4** [CraftTweaker/CraftTweaker-Documentation#530]
can someone help me, im trying change ProjectE crafting and this happens
''ERROR: [crafttweaker : SIDE_CLIENT]: Error parsing .zs:4 -- ]
or , expected''

https://pastebin.com/3XEqBRid

**Comment by Witixin1512** [comment]
Hi! This repository is for issues with the documentation, if you require script support, feel free to drop by the Discord Server and get help there:
https://discord.blamejared.com/
