### ISSUE TITLE
MCTag Addid dies not work but add does

### ISSUE THREAD

**Issue by Joshernoob** [CraftTweaker/CraftTweaker-Documentation#531]
Most likly just forgot to update but on this page https://docs.blamejared.com/1.19/pl/vanilla/api/tag/MCTag were it says addId if  you just copy cast the code into a script and reload it eorors on the addId part. howver removing Id fixes this hence me thinking its a Documentation error

**Comment by Witixin1512** [comment]
Can you show the full script you were using to do that please?

**Comment by Joshernoob** [comment]
> Can you show the full script you were using to do that please?

https://pastebin.com/vmvZdKLq

**Comment by Witixin1512** [comment]
There's nothing wrong with that, it is working as intended. 
If you join the discord located at https://discord.blamejared.com/ I can explain this to you in more detail than a github conversation can (it will be much faster and we won't get more emails on every message).
