### ISSUE TITLE
Update of Loader Tag Preprocessor

### ISSUE THREAD

**Issue by Laifsyn** [CraftTweaker/CraftTweaker-Documentation#532]
### Describe the feature you'd like

With the addition of the Loader Tag Preprocessor, I believe that the docs for Loader Preprocessor should be updated
<https://docs.blamejared.com/1.18/tr/zencode/Preprocessors/LoaderPreprocessor>

### Modloader

All

**Comment by Witixin1512** [comment]
https://docs.blamejared.com/1.19/en/zencode/TagsLoader

**Comment by Witixin1512** [comment]
For context, 1.18 docs will also be coming soon with more details, but it is now documented into the latest version of the docs.
