### ISSUE TITLE
1.12.2 EntityLivingFallEvent distance getter misspelled as disance

### ISSUE THREAD

**Issue by BBLKepling** [CraftTweaker/CraftTweaker-Documentation#536]
https://docs.blamejared.com/1.12/en/Vanilla/Events/Events/EntityLivingFall

https://github.com/CraftTweaker/CraftTweaker/blob/1.12/CraftTweaker2-API/src/main/java/crafttweaker/api/event/EntityLivingFallEvent.java

**Comment by democat3457** [comment]
can be closed with https://github.com/CraftTweaker/CraftTweaker-Documentation/commit/e37aedb6253d86abcdc3b26ac40000a55ab8b7e4
