### ISSUE TITLE
The FluidStack[] for the create mixer is listed as optional, even though its required

### ISSUE THREAD

**Issue by tuc56** [CraftTweaker/CraftTweaker-Documentation#552]
Just noticed nobody had made a github issue for that yet, so Ill go ahead and do that

**Comment by democat3457** [comment]
The [source](https://github.com/jaredlll08/CreateTweaker/blob/1.20.1/common/src/main/java/com/blamejared/createtweaker/recipe/manager/MixingManager.java#L119) says that it is, though... 🤔
