### ISSUE TITLE
CTEventManager docs page not under forge/api/events in 1.20.x branches

### ISSUE THREAD

**Issue by blockgoblin31** [CraftTweaker/CraftTweaker-Documentation#563]
Unless I’m completely blind, there isn’t a CTEventManager docs page on 1.20.x

**Comment by jaredlll08** [comment]
In 1.20.x we moved the CTEventManager to https://docs.blamejared.com/1.20.1/en/vanilla/api/event/EventManager, as you can now register events in for fabric.

It isn't listed on the page, but you can get an instance by using the `events` global
