### ISSUE TITLE
Site Shows all upercase for code when  part needs to be lowered

### ISSUE THREAD

**Issue by Joshernoob** [CraftTweaker/CraftTweaker-Documentation#564]
https://docs.blamejared.com/1.16/en/mods/other_mods

![Screenshot 2024-02-21 001435](https://github.com/CraftTweaker/CraftTweaker-Documentation/assets/64944433/7c8d7dd8-27d5-4f1d-944b-e8400729308b)
![Screenshot 2024-02-21 001452](https://github.com/CraftTweaker/CraftTweaker-Documentation/assets/64944433/e754863e-73de-4b16-bb3f-bf137b06da3f)

Its a small part but the Json part on site shows All caps but only way seems to work is Json, form what i've seen of how the codes formated that seems to fit a bit better aas well.

small thing but will stump many people looking to use Json code with craftweaker and running to the documents

**Comment by jaredlll08** [comment]
For 1.16 that syntax is correct, I only made it lowercase in newer versions, I'm not sure what version you are using, but if `addJsonRecipe` works, then it isn't 1.16.
