### ISSUE TITLE
Events page doesn't link to IEventManager correctly. 

### ISSUE THREAD

**Issue by darkhax** [CraftTweaker/CraftTweaker-Documentation#73]
1. Go to https://crafttweaker.readthedocs.io/en/latest/#Vanilla/Events/Events/
2. Click on the IEventManager hyperlink
3. URL changes, but the contents are the same.
4. Add a / to the end of the url and you go to the right page.

**Comment by SlyCedix** [comment]
So far, this appears to occur on every single hyper link on the docs, or at least, I haven't found any that it does not occur on.

**Comment by kindlich** [comment]
Seems to have somethign to do with the hppts version, in hppt it works fine without that slash...
