### ISSUE TITLE
How to inherit an IItemStack's texture

### ISSUE THREAD

**Issue by MessyConfessor** [CraftTweaker/CraftTweaker-Documentation#82]
I'm looking to do something that -- I think -- should be very basic and well within the capabilities of CraftTweaker. Unfortunately, it is not well within *my* capabilities, lol. I've scoured the documentation, but can't figure it out.

Here's my script:

```
import crafttweaker.item.IItemDefinition;
import crafttweaker.item.IItemStack;

val geodeDefinition = <thermalfoundation:geode>.definition;

geodeDefinition.makeStack(1);
<thermalfoundation:geode:1>.displayName = "Firey Geode";
```
Basically, Thermal Foundation's geodes exist only as a metadata-0 item. I'm looking to create variants of them that can be found in different biomes (using Dropt to edit mining drops).

When I run the game with the above script, I get mixed results:

1. The Firey Geode does not appear in JEI or Creative Tabs (bad, I guess? Not very important to me.)
2. When I use /nbtedit item to change a geode in my hand to metadata-1, it renames itself Firey Geode (good!)
3. It loses both the model and the texture of the base geode, becoming a pink and black box (very bad)

I was under the (apparently mistaken) impression that starting the creation with the original geode's definition would cause it to automatically inherit any elements that I didn't specifically change, such as the texturing.

How far am I from being able to live my dream of geode variants as biome-specific loot?

**Comment by jaredlll08** [comment]
"How far am I from being able to live my dream of geode variants as biome specific loot?"

Kinda far.

CraftTweaker doesn't add new items, and while it is possible to give a preexisting item with a Metadata value that isn't used, mods only texture the Metadata they need, so it wouldn't have a texture. 


Take a look at contenttweaker

**Comment by MessyConfessor** [comment]
Will do, thanks.
