### ISSUE TITLE
Request: Add Integrated Dynamics documentation

### ISSUE THREAD

**Issue by TheDeviantCrafter** [CraftTweaker/CraftTweaker-Documentation#84]
The CraftTweaker documentation for Integrated Dynamics can be found on the mod's Github, but it's a little hard to find. I'd like this site to be the central location for this sort of thing.

You can find the original documents here: https://github.com/CyclopsMC/IntegratedDynamics/wiki/MineTweaker

**Comment by kindlich** [comment]
Send me some examples and I'll look into it.
Alternatively, everyone is free to start a PR to add stuff to the CrT-wiki.
