### ISSUE TITLE
Minor error in MobStages documentation

### ISSUE THREAD

**Issue by MightyBidoof** [CraftTweaker/CraftTweaker-Documentation#90]
I was directed by Jared to put this here, so it's (mostly) copy-pasted directly from what i put in the discord.

the example scripts under "Global Options" for MobStages are written incorrectly
``// mod.MobStages.addReplacement(String entityId, String replacementId);
mod.MobStages.addReplacement("minecraft:zombie, "minecraft:slime);`` example

all of them have the mod.MobStages, which should be mods.MobStages

and the ("minecraft:zombie, "minecraft:slime); are both missing a " on the ends of both entries.

**Comment by kindlich** [comment]
Normally Id fix that myself but am.currently unable to do so.

You can fix it yourself though, by using HitHubs online editor and PR system:

1) Locate the file (`docs/Mods/GameStages/MobStages/MobStages.md`)
2) Open the file in the GH code view
3) Click on the Edit button
4) Edit the file to your liking
5) Fill in the commit message and click.commit, it should create a PR automatically. (Note, include `closes #90` in your commit/PR title or description, it'll automatically close this issue once merged.
