### ISSUE TITLE
[Suggestion] Furnace Removal Based On Input

### ISSUE THREAD

**Issue by UnlimatedStone9** [CraftTweaker/CraftTweaker-Documentation#94]
Hey there, I was curious, is it possible you could implement a script that allows the user to remove a furnace recipe based on the input, this would combat the issues with outputs from mods such as Tough As Nails that are awkward if not impossible to remove
(Tough As Nails pure water bucket cannot be removed because the item ID is just forge:bucketFilled, Some other mods would have this issue)
It would also allows users to remove recipes with multiple outputs, Eg:
Mod A implements a recipe using quarts to make silicon
Mod B implements a recipe using quartz to make coal

using a script along the lines of this would allow all recipes using quartz to be removed
furnace.removeInput(<minecraft:quartz>)

Thanks for the work done to the mod so far!            -UnlimatedStone9

**Comment by jaredlll08** [comment]
wrong repo, this is for documentation.

Just use the input specific removal
https://crafttweaker.readthedocs.io/en/latest/#Vanilla/Recipes/Furnace/Recipes_Furnace/

**Comment by UnlimatedStone9** [comment]
I don't see any input specific removal scripts so I'm not quite sure what you mean by that

**Comment by jaredlll08** [comment]
`furnace.remove(IIngredient output, IIngredient input);`

you would need to specify both input and output.
